# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :metadata do
  deliver(metadata_path: "fastlane/meta",
    skip_metadata: false)
end

lane :beta do
  sync_code_signing(type: "appstore", readonly: true)
  # snapshot
  build_ios_app(
    scheme: "OsmoTagger",
    destination: 'generic/platform=iOS',
  ) # Build your app - more options available
  upload_to_testflight(skip_submission:true,
    skip_waiting_for_build_processing:true
  )
end

lane :screenshots do
  deliver(
    skip_screenshots: false,
    overwrite_screenshots: true)
end

lane :load_profiles do
  match(type: "development", readonly: true)
  match(type: "appstore", readonly: true)
end

lane :refresh_profiles do
  match(type: "development", force_for_new_devices: true)
  match(type: "appstore")
end