# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Deploy a OpenStreetEditor to the Testflight"
  lane :beta_free do
    sync_code_signing(type: "appstore", app_identifier: ["com.bodunov.galileo", "com.bodunov.galileo.SiriIntents"], readonly: true)
    # snapshot
    build_ios_app(
      scheme: "OpenStreetEditor",
      destination: 'generic/platform=iOS',
    ) # Build your app - more options available
    upload_to_testflight(skip_submission:true,
      skip_waiting_for_build_processing:true,
      app_identifier: "com.openstreet.editor"
    )
    # sentry_upload_dsym(
    #   org_slug: 'guru',
    #   project_slug: 'guru-maps-ios',
    # )
  end

end
